/**
 * Comprehensive language configuration for Snippet Bubbles.
 * Includes all 40+ supported languages with syntax rules, formatting options, and metadata.
 */

export interface LanguageConfig {
  id: string;
  name: string;
  aliases: string[];
  extensions: string[];
  category: "backend" | "frontend" | "database" | "markup" | "config" | "other";
  keywords: Set<string>;
  commentSingle: string;
  commentMultiStart: string;
  commentMultiEnd: string;
  stringDelimiters: string[];
  formatter?: "prettier" | "black" | "gofmt" | "rustfmt" | "shfmt" | "sqlformat" | "none";
  highlightColor: {
    keyword: string;
    string: string;
    comment: string;
    number: string;
    function: string;
    type: string;
  };
}

const LANGUAGES: Record<string, LanguageConfig> = {
  javascript: {
    id: "javascript",
    name: "JavaScript",
    aliases: ["js"],
    extensions: [".js", ".mjs"],
    category: "frontend",
    keywords: new Set([
      "const", "let", "var", "function", "return", "if", "else", "for", "while", "do",
      "switch", "case", "break", "continue", "new", "this", "class", "extends", "import",
      "export", "default", "from", "async", "await", "try", "catch", "finally", "throw",
      "typeof", "instanceof", "in", "of", "yield", "void", "delete", "true", "false",
      "null", "undefined", "super", "static", "get", "set", "constructor",
    ]),
    commentSingle: "//",
    commentMultiStart: "/*",
    commentMultiEnd: "*/",
    stringDelimiters: ['"', "'", "`"],
    formatter: "prettier",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  typescript: {
    id: "typescript",
    name: "TypeScript",
    aliases: ["ts"],
    extensions: [".ts", ".tsx"],
    category: "frontend",
    keywords: new Set([
      "const", "let", "var", "function", "return", "if", "else", "for", "while", "do",
      "switch", "case", "break", "continue", "new", "this", "class", "extends", "import",
      "export", "default", "from", "async", "await", "try", "catch", "finally", "throw",
      "typeof", "instanceof", "in", "of", "yield", "void", "delete", "true", "false",
      "null", "undefined", "interface", "type", "enum", "implements", "abstract",
      "public", "private", "protected", "readonly", "static", "super", "get", "set",
    ]),
    commentSingle: "//",
    commentMultiStart: "/*",
    commentMultiEnd: "*/",
    stringDelimiters: ['"', "'", "`"],
    formatter: "prettier",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  python: {
    id: "python",
    name: "Python",
    aliases: ["py"],
    extensions: [".py"],
    category: "backend",
    keywords: new Set([
      "def", "lambda", "pass", "with", "as", "is", "not", "and", "or", "None",
      "True", "False", "print", "self", "elif", "except", "raise", "global", "nonlocal",
      "import", "from", "class", "return", "if", "else", "for", "while", "break", "continue",
      "try", "finally", "yield", "assert", "del", "in",
    ]),
    commentSingle: "#",
    commentMultiStart: '"""',
    commentMultiEnd: '"""',
    stringDelimiters: ['"', "'"],
    formatter: "black",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  java: {
    id: "java",
    name: "Java",
    aliases: ["java"],
    extensions: [".java"],
    category: "backend",
    keywords: new Set([
      "public", "private", "protected", "static", "final", "class", "interface", "extends",
      "implements", "new", "this", "super", "return", "if", "else", "for", "while", "do",
      "switch", "case", "break", "continue", "try", "catch", "finally", "throw", "throws",
      "import", "package", "void", "int", "long", "double", "float", "boolean", "char",
      "String", "true", "false", "null", "instanceof", "abstract", "synchronized",
    ]),
    commentSingle: "//",
    commentMultiStart: "/*",
    commentMultiEnd: "*/",
    stringDelimiters: ['"'],
    formatter: "none",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  csharp: {
    id: "csharp",
    name: "C#",
    aliases: ["cs", "csharp"],
    extensions: [".cs"],
    category: "backend",
    keywords: new Set([
      "public", "private", "protected", "internal", "static", "class", "interface", "struct",
      "enum", "namespace", "using", "new", "this", "base", "return", "if", "else", "for",
      "while", "do", "switch", "case", "break", "continue", "try", "catch", "finally",
      "throw", "async", "await", "void", "int", "long", "double", "float", "bool", "string",
      "true", "false", "null", "abstract", "sealed", "virtual", "override", "const",
    ]),
    commentSingle: "//",
    commentMultiStart: "/*",
    commentMultiEnd: "*/",
    stringDelimiters: ['"'],
    formatter: "none",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  cpp: {
    id: "cpp",
    name: "C++",
    aliases: ["cc", "cxx", "c++"],
    extensions: [".cpp", ".cc", ".cxx", ".h", ".hpp"],
    category: "backend",
    keywords: new Set([
      "class", "struct", "union", "enum", "namespace", "template", "typename", "public",
      "private", "protected", "virtual", "override", "final", "const", "volatile", "static",
      "extern", "inline", "return", "if", "else", "for", "while", "do", "switch", "case",
      "break", "continue", "try", "catch", "throw", "new", "delete", "this", "nullptr",
      "true", "false", "void", "int", "long", "double", "float", "bool", "char",
    ]),
    commentSingle: "//",
    commentMultiStart: "/*",
    commentMultiEnd: "*/",
    stringDelimiters: ['"'],
    formatter: "none",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  c: {
    id: "c",
    name: "C",
    aliases: ["c"],
    extensions: [".c", ".h"],
    category: "backend",
    keywords: new Set([
      "int", "char", "float", "double", "void", "long", "short", "signed", "unsigned",
      "struct", "union", "enum", "typedef", "const", "volatile", "static", "extern",
      "return", "if", "else", "for", "while", "do", "switch", "case", "break", "continue",
      "goto", "sizeof", "true", "false", "NULL",
    ]),
    commentSingle: "//",
    commentMultiStart: "/*",
    commentMultiEnd: "*/",
    stringDelimiters: ['"'],
    formatter: "none",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  go: {
    id: "go",
    name: "Go",
    aliases: ["golang"],
    extensions: [".go"],
    category: "backend",
    keywords: new Set([
      "package", "import", "func", "type", "interface", "struct", "const", "var", "return",
      "if", "else", "for", "range", "switch", "case", "default", "break", "continue",
      "goto", "defer", "go", "chan", "select", "map", "slice", "true", "false", "nil",
      "iota", "make", "len", "cap", "append", "copy", "delete", "complex", "real", "imag",
    ]),
    commentSingle: "//",
    commentMultiStart: "/*",
    commentMultiEnd: "*/",
    stringDelimiters: ['"', "`"],
    formatter: "gofmt",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  rust: {
    id: "rust",
    name: "Rust",
    aliases: ["rs"],
    extensions: [".rs"],
    category: "backend",
    keywords: new Set([
      "fn", "pub", "mod", "use", "impl", "trait", "struct", "enum", "type", "const",
      "static", "mut", "ref", "move", "return", "if", "else", "match", "for", "while",
      "loop", "break", "continue", "unsafe", "async", "await", "where", "as", "in",
      "true", "false", "self", "Self", "super", "crate", "dyn",
    ]),
    commentSingle: "//",
    commentMultiStart: "/*",
    commentMultiEnd: "*/",
    stringDelimiters: ['"'],
    formatter: "rustfmt",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  kotlin: {
    id: "kotlin",
    name: "Kotlin",
    aliases: ["kt"],
    extensions: [".kt", ".kts"],
    category: "backend",
    keywords: new Set([
      "fun", "val", "var", "class", "object", "interface", "enum", "sealed", "data",
      "companion", "override", "abstract", "open", "final", "private", "public", "protected",
      "internal", "return", "if", "else", "when", "for", "while", "do", "break", "continue",
      "try", "catch", "finally", "throw", "import", "package", "as", "is", "in", "true",
      "false", "null", "suspend", "inline", "infix", "operator", "const", "expect", "actual",
    ]),
    commentSingle: "//",
    commentMultiStart: "/*",
    commentMultiEnd: "*/",
    stringDelimiters: ['"'],
    formatter: "none",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  swift: {
    id: "swift",
    name: "Swift",
    aliases: ["swift"],
    extensions: [".swift"],
    category: "backend",
    keywords: new Set([
      "func", "var", "let", "class", "struct", "enum", "protocol", "extension", "init",
      "deinit", "subscript", "static", "final", "override", "private", "public", "internal",
      "fileprivate", "open", "mutating", "nonmutating", "return", "if", "else", "switch",
      "case", "for", "while", "repeat", "break", "continue", "fallthrough", "defer", "do",
      "try", "catch", "throw", "guard", "where", "as", "is", "in", "true", "false", "nil",
    ]),
    commentSingle: "//",
    commentMultiStart: "/*",
    commentMultiEnd: "*/",
    stringDelimiters: ['"'],
    formatter: "none",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  php: {
    id: "php",
    name: "PHP",
    aliases: ["php"],
    extensions: [".php"],
    category: "backend",
    keywords: new Set([
      "function", "return", "if", "else", "elseif", "switch", "case", "for", "foreach",
      "while", "do", "break", "continue", "try", "catch", "finally", "throw", "class",
      "interface", "trait", "extends", "implements", "public", "private", "protected",
      "static", "const", "var", "new", "this", "self", "parent", "namespace", "use",
      "echo", "print", "isset", "empty", "die", "exit", "include", "require", "true",
      "false", "null", "array", "list", "global", "yield",
    ]),
    commentSingle: "//",
    commentMultiStart: "/*",
    commentMultiEnd: "*/",
    stringDelimiters: ['"', "'"],
    formatter: "none",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  sql: {
    id: "sql",
    name: "SQL",
    aliases: ["sql"],
    extensions: [".sql"],
    category: "database",
    keywords: new Set([
      "SELECT", "FROM", "WHERE", "INSERT", "INTO", "VALUES", "UPDATE", "SET", "DELETE",
      "CREATE", "TABLE", "ALTER", "DROP", "INDEX", "VIEW", "DATABASE", "SCHEMA",
      "JOIN", "LEFT", "RIGHT", "INNER", "OUTER", "ON", "AND", "OR", "NOT", "IN",
      "BETWEEN", "LIKE", "IS", "NULL", "GROUP", "BY", "HAVING", "ORDER", "ASC", "DESC",
      "LIMIT", "OFFSET", "DISTINCT", "UNION", "INTERSECT", "EXCEPT", "CASE", "WHEN",
      "THEN", "ELSE", "END", "AS", "WITH", "RECURSIVE", "PRIMARY", "KEY", "FOREIGN",
      "UNIQUE", "CHECK", "DEFAULT", "CONSTRAINT", "TRIGGER", "PROCEDURE", "FUNCTION",
    ]),
    commentSingle: "--",
    commentMultiStart: "/*",
    commentMultiEnd: "*/",
    stringDelimiters: ["'"],
    formatter: "sqlformat",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  mysql: {
    id: "mysql",
    name: "MySQL",
    aliases: ["mysql"],
    extensions: [".sql"],
    category: "database",
    keywords: new Set([
      "SELECT", "FROM", "WHERE", "INSERT", "INTO", "VALUES", "UPDATE", "SET", "DELETE",
      "CREATE", "TABLE", "ALTER", "DROP", "INDEX", "DATABASE", "USE", "SHOW", "DESCRIBE",
      "JOIN", "LEFT", "RIGHT", "INNER", "CROSS", "ON", "AND", "OR", "NOT", "IN",
      "BETWEEN", "LIKE", "IS", "NULL", "GROUP", "BY", "HAVING", "ORDER", "ASC", "DESC",
      "LIMIT", "OFFSET", "DISTINCT", "UNION", "CASE", "WHEN", "THEN", "ELSE", "END",
      "PRIMARY", "KEY", "FOREIGN", "UNIQUE", "AUTO_INCREMENT", "DEFAULT", "ENGINE",
    ]),
    commentSingle: "--",
    commentMultiStart: "/*",
    commentMultiEnd: "*/",
    stringDelimiters: ["'"],
    formatter: "sqlformat",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  postgresql: {
    id: "postgresql",
    name: "PostgreSQL",
    aliases: ["postgres", "psql"],
    extensions: [".sql"],
    category: "database",
    keywords: new Set([
      "SELECT", "FROM", "WHERE", "INSERT", "INTO", "VALUES", "UPDATE", "SET", "DELETE",
      "CREATE", "TABLE", "ALTER", "DROP", "INDEX", "SCHEMA", "DATABASE", "VIEW",
      "FUNCTION", "PROCEDURE", "TRIGGER", "RULE", "CONSTRAINT", "JOIN", "LEFT", "RIGHT",
      "INNER", "CROSS", "ON", "AND", "OR", "NOT", "IN", "BETWEEN", "LIKE", "ILIKE",
      "IS", "NULL", "GROUP", "BY", "HAVING", "ORDER", "ASC", "DESC", "LIMIT", "OFFSET",
      "DISTINCT", "UNION", "INTERSECT", "EXCEPT", "CASE", "WHEN", "THEN", "ELSE", "END",
      "WITH", "RECURSIVE", "LATERAL", "WINDOW", "OVER", "PARTITION", "ROWS", "RANGE",
    ]),
    commentSingle: "--",
    commentMultiStart: "/*",
    commentMultiEnd: "*/",
    stringDelimiters: ["'"],
    formatter: "sqlformat",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  bash: {
    id: "bash",
    name: "Bash",
    aliases: ["sh", "shell"],
    extensions: [".sh", ".bash"],
    category: "backend",
    keywords: new Set([
      "if", "then", "else", "elif", "fi", "for", "do", "done", "while", "until", "case",
      "esac", "function", "return", "export", "local", "readonly", "declare", "typeset",
      "unset", "shift", "break", "continue", "exit", "trap", "source", "eval", "exec",
      "echo", "printf", "read", "cd", "pwd", "ls", "mkdir", "rm", "cp", "mv", "cat",
      "grep", "sed", "awk", "cut", "sort", "uniq", "find", "xargs", "true", "false",
    ]),
    commentSingle: "#",
    commentMultiStart: "",
    commentMultiEnd: "",
    stringDelimiters: ['"', "'"],
    formatter: "shfmt",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  html: {
    id: "html",
    name: "HTML",
    aliases: ["html"],
    extensions: [".html", ".htm"],
    category: "markup",
    keywords: new Set([
      "html", "head", "body", "title", "meta", "link", "script", "style", "div", "span",
      "p", "a", "img", "button", "input", "form", "label", "select", "textarea", "table",
      "tr", "td", "th", "ul", "ol", "li", "h1", "h2", "h3", "h4", "h5", "h6", "header",
      "footer", "nav", "main", "section", "article", "aside", "figure", "figcaption",
    ]),
    commentSingle: "",
    commentMultiStart: "<!--",
    commentMultiEnd: "-->",
    stringDelimiters: ['"', "'"],
    formatter: "prettier",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  css: {
    id: "css",
    name: "CSS",
    aliases: ["css"],
    extensions: [".css"],
    category: "frontend",
    keywords: new Set([
      "color", "background", "border", "margin", "padding", "width", "height", "display",
      "position", "top", "left", "right", "bottom", "font", "text", "align", "justify",
      "flex", "grid", "transform", "transition", "animation", "hover", "active", "focus",
      "before", "after", "nth-child", "nth-of-type", "first-child", "last-child",
    ]),
    commentSingle: "",
    commentMultiStart: "/*",
    commentMultiEnd: "*/",
    stringDelimiters: ['"', "'"],
    formatter: "prettier",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  json: {
    id: "json",
    name: "JSON",
    aliases: ["json"],
    extensions: [".json"],
    category: "config",
    keywords: new Set(["true", "false", "null"]),
    commentSingle: "",
    commentMultiStart: "",
    commentMultiEnd: "",
    stringDelimiters: ['"'],
    formatter: "prettier",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  yaml: {
    id: "yaml",
    name: "YAML",
    aliases: ["yml", "yaml"],
    extensions: [".yaml", ".yml"],
    category: "config",
    keywords: new Set(["true", "false", "null", "yes", "no", "on", "off"]),
    commentSingle: "#",
    commentMultiStart: "",
    commentMultiEnd: "",
    stringDelimiters: ['"', "'"],
    formatter: "none",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  xml: {
    id: "xml",
    name: "XML",
    aliases: ["xml"],
    extensions: [".xml"],
    category: "markup",
    keywords: new Set([]),
    commentSingle: "",
    commentMultiStart: "<!--",
    commentMultiEnd: "-->",
    stringDelimiters: ['"', "'"],
    formatter: "prettier",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  markdown: {
    id: "markdown",
    name: "Markdown",
    aliases: ["md"],
    extensions: [".md", ".markdown"],
    category: "markup",
    keywords: new Set(["#", "##", "###", "####", "#####", "######", "-", "*", "+"]),
    commentSingle: "",
    commentMultiStart: "",
    commentMultiEnd: "",
    stringDelimiters: ["`"],
    formatter: "prettier",
    highlightColor: {
      keyword: "#DC2626",
      string: "#22C55E",
      comment: "#6B7280",
      number: "#F59E0B",
      function: "#3B82F6",
      type: "#A78BFA",
    },
  },
  plaintext: {
    id: "plaintext",
    name: "Plaintext",
    aliases: ["txt", "text"],
    extensions: [".txt"],
    category: "other",
    keywords: new Set([]),
    commentSingle: "",
    commentMultiStart: "",
    commentMultiEnd: "",
    stringDelimiters: [],
    formatter: "none",
    highlightColor: {
      keyword: "#6B7280",
      string: "#6B7280",
      comment: "#6B7280",
      number: "#6B7280",
      function: "#6B7280",
      type: "#6B7280",
    },
  },
};

// Additional languages (abbreviated configs for space)
const ADDITIONAL_LANGUAGES: Record<string, Partial<LanguageConfig>> = {
  r: { name: "R", category: "backend", commentSingle: "#" },
  perl: { name: "Perl", category: "backend", commentSingle: "#" },
  ruby: { name: "Ruby", category: "backend", commentSingle: "#" },
  dart: { name: "Dart", category: "backend", commentSingle: "//" },
  julia: { name: "Julia", category: "backend", commentSingle: "#" },
  scheme: { name: "Scheme", category: "backend", commentSingle: ";" },
  lisp: { name: "Lisp", category: "backend", commentSingle: ";" },
  scala: { name: "Scala", category: "backend", commentSingle: "//" },
  haskell: { name: "Haskell", category: "backend", commentSingle: "--" },
  lua: { name: "Lua", category: "backend", commentSingle: "--" },
  nim: { name: "Nim", category: "backend", commentSingle: "#" },
  erlang: { name: "Erlang", category: "backend", commentSingle: "%" },
  dockerfile: { name: "Dockerfile", category: "config", commentSingle: "#" },
  scss: { name: "SCSS", category: "frontend", commentSingle: "//" },
  latex: { name: "LaTeX", category: "markup", commentSingle: "%" },
  assembly: { name: "Assembly", category: "backend", commentSingle: ";" },
  bat: { name: "Batch", category: "backend", commentSingle: "REM" },
  graphql: { name: "GraphQL", category: "backend", commentSingle: "#" },
  mariadb: { name: "MariaDB SQL", category: "database", commentSingle: "--" },
  http: { name: "HTTP", category: "backend", commentSingle: "#" },
  sass: { name: "Sass", category: "frontend", commentSingle: "//" },
  powershell: { name: "PowerShell", category: "backend", commentSingle: "#" },
  curl: { name: "cURL", category: "backend", commentSingle: "#" },
  lobster: { name: "Lobster", category: "backend", commentSingle: "//" },
};

export function getLanguageConfig(languageId: string): LanguageConfig | null {
  const lang = LANGUAGES[languageId.toLowerCase()];
  if (lang) return lang;

  const additional = ADDITIONAL_LANGUAGES[languageId.toLowerCase()];
  if (additional) {
    return {
      id: languageId.toLowerCase(),
      name: additional.name || languageId,
      aliases: [languageId.toLowerCase()],
      extensions: [],
      category: additional.category || "other",
      keywords: additional.keywords || new Set([]),
      commentSingle: additional.commentSingle || "//",
      commentMultiStart: additional.commentMultiStart || "/*",
      commentMultiEnd: additional.commentMultiEnd || "*/",
      stringDelimiters: additional.stringDelimiters || ['"'],
      formatter: additional.formatter || "none",
      highlightColor: additional.highlightColor || {
        keyword: "#DC2626",
        string: "#22C55E",
        comment: "#6B7280",
        number: "#F59E0B",
        function: "#3B82F6",
        type: "#A78BFA",
      },
    } as LanguageConfig;
  }

  return null;
}

export function getAllLanguages(): LanguageConfig[] {
  return Object.values(LANGUAGES);
}

export function getLanguagesByCategory(category: string): LanguageConfig[] {
  return Object.values(LANGUAGES).filter((lang) => lang.category === category);
}

export function detectLanguageFromExtension(extension: string): LanguageConfig | null {
  const ext = extension.toLowerCase();
  const lang = Object.values(LANGUAGES).find((l) => l.extensions.includes(ext));
  return lang || null;
}
